#!/bin/bash

FONT_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip"
TEMP_DIR="/tmp/fonts"
FONT_NAME="JetBrainsMono"
FONT_DEST_DIR="$HOME/.local/share/fonts"  

mkdir -p "$TEMP_DIR"

wget "$FONT_URL" -O "$TEMP_DIR/$FONT_NAME.zip"

unzip "$TEMP_DIR/$FONT_NAME.zip" -d "$TEMP_DIR/$FONT_NAME"

mkdir -p "$FONT_DEST_DIR"
cp "$TEMP_DIR/$FONT_NAME"/*.ttf "$FONT_DEST_DIR/"

fc-cache -fv

rm -rf "$TEMP_DIR"


